layout_spectrum: 0.9204261
color:
  saturation: 0.9115072
  lightness: 0.540601
  brandStrength: 0.5115722
  brandColors:
    - '#000000'
    - '#6D6E71'
    - '#F39331'
    - '#1B1B1B'
    - '#AEAFB2'
  rhythmicContrast: 0.4023527
typography_spectrum: 0.2305764
name: THEINSIGHTSCO
