name: THEINSIGHTSCO
favicon: null
layout_spectrum: 0.9204261
typography_spectrum: 0.2305764
title: The Insights Co.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6D6E71'
    - '#F39331'
    - '#1B1B1B'
    - '#AEAFB2'
  brandStrength: 0.5115722
  lightness: 0.540601
  saturation: 0.9115072
  rhythmicContrast: 0.4023527
purpose: []
