name: THEINSIGHTSCO
favicon: null
layout_spectrum: 0.9204261
typography_spectrum: 0.13562
title: The Insights Co.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6e71'
    - '#ff8d00'
    - '#a9aaad'
    - '#dddddd'
    - '#ffbd7b'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
